HAI
I HAS A HEIGHT
I HAS A WEIGHT
I HAS A BMI
VISIBLE "ENTER YOUR HEIGHT IN METERS"
GIMMEH HEIGHT
VISIBLE "ENTER YOUR WEIGHT IN KILOGRAMS"
GIMMEH WEIGHT
BMI R QUOSHUNT OF WEIGHT AN PRODUKT OF HEIGHT AN HEIGHT
VISIBLE BMI
KTHXBYE
