HAI
I HAS A a ITZ 22
I HAS A b ITZ 76
I HAS A c ITZ 18
I HAS A IN
VISIBLE "ENTER A NUMBER"
GIMMEH IN
BOTH SAEM MOD OF IN AN 2 AN 0
O RLY?
YA RLY
VISIBLE SMOOSH IN AN " IS EVEN"
NO WAI
VISIBLE SMOOSH IN AN "IS ODD"
OIC
KTHXBYE
