HAI
SUM OF PRODUKT OF 2 AN 7 AN DIFF OF 3 AN 5
VAR R SUM OF 2 AN DIFF OF 7 AN 10
VISIBLE SUM OF 1 AN 100
VISIBLE BOTH OF WIN AN FAIL
VISIBLE NOT FAIL
VISIBLE EITHER OF WIN AN FAIL
VISIBLE EITHER OF FAIL AN FAIL
VISIBLE EITHER OF FAIL AN BOTH OF FAIL AN FAIL
I HAS A PRUTO ITZ A NUMBR
I HAS A VARIABLE ITZ A YARN
KTHXBYE
